name: ManagerAgent

on:
  issues:
    types: [opened, reopened, edited]

permissions:
  contents: write          # allow branch pushes
  pull-requests: write     # allow opening PRs

jobs:
  manage:
    if: github.event.issue.state == 'open'
    runs-on: ubuntu-latest

    steps:
      # ───────────────────────────────
      # 0. Check out the repo
      - uses: actions/checkout@v4

      # ───────────────────────────────
      # 1. Build a prompt from the issue
      - name: Build prompt
        id: prompt
        run: |
          cat <<EOF > prompt.txt
          Repository: ${{ github.repository }}
          Issue #${{ github.event.issue.number }} – ${{ github.event.issue.title }}

          ${{ github.event.issue.body }}
          EOF

      # ───────────────────────────────
      # 2. Install OpenAI client
      - name: Install OpenAI client
        run: pip install --quiet openai

      # ───────────────────────────────
      # 3. Call OpenAI and create files
      - name: Generate files with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'PY'
          import os, json, pathlib, openai, sys
          openai.api_key = os.environ["OPENAI_API_KEY"]

          with open("prompt.txt") as f:
              user_prompt = f.read()

          resp = openai.ChatCompletion.create(
              model="gpt-4o-mini",
              messages=[
                {"role":"system","content":(
                  "You are an autonomous coding agent. "
                  "Respond ONLY with valid JSON—an array of objects "
                  "[{\"path\":\"...\",\"content\":\"...\"}]. "
                  "No markdown, no prose."
                )},
                {"role":"user","content":user_prompt}
              ],
              max_tokens=1500
          )

          try:
              files = json.loads(resp.choices[0].message.content)
          except json.JSONDecodeError:
              print("ERROR: Model response is not valid JSON")
              print(resp.choices[0].message.content)
              sys.exit(1)

          for f in files:
              p = pathlib.Path(f["path"])
              p.parent.mkdir(parents=True, exist_ok=True)
              p.write_text(f["content"])
          PY

      # ───────────────────────────────
      # 4. Commit & push a new branch
      - name: Commit & push branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="agent/${{ github.event.issue.number }}-${{ github.run_id }}"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "Agent output for #${{ github.event.issue.number }}"
          # use GITHUB_TOKEN for auth
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git push -u origin "$BRANCH"

      # ───────────────────────────────
      # 5. Open a pull request to main
      - name: Open pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Agent PR for #${{ github.event.issue.number }}" \
            --body "Automated changes generated by ManagerAgent." \
            --head "$BRANCH" \
            --base main
